CREATE USER ORM IDENTIFIED BY ORM DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO ORM;
CONNECT ORM/ORM;

DROP TABLE LIBROS CASCADE CONSTRAINTS;
DROP TABLE SOCIOS CASCADE CONSTRAINTS;
DROP TABLE PRESTAMOS CASCADE CONSTRAINTS;
CREATE TABLE LIBROS (
	ID_LIBRO NUMBER(4),
	TITULO VARCHAR2(30),
	NUM_EJEMPLARES NUMBER(2),
	EDITORIAL VARCHAR2(20),
	NUM_PAGINAS NUMBER(4),
	FECHA_EDICION DATE,
	CONSTRAINT PK_LIBRO PRIMARY KEY(ID_LIBRO));

CREATE TABLE SOCIOS (
	ID_SOCIO NUMBER(4),
	NOMBRE_SOCIO VARCHAR2(30),
	EDAD NUMBER(3),
	DIRECCION VARCHAR2(40),
	CONSTRAINT PK_SOCIOS PRIMARY KEY (ID_SOCIO));


CREATE TABLE PRESTAMOS (
	ID_LIBRO NUMBER(4),
	ID_SOCIO NUMBER(4),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	CONSTRAINT PK_PRESTAMOS PRIMARY KEY(ID_LIBRO, ID_SOCIO),
	CONSTRAINT FK_PRESTAMOS_LIBROS FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO),
	CONSTRAINT FK_PRESTAMOS_SOCIOS FOREIGN KEY(ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO)
	);
