package clases;
// Generated 31-ene-2017 10:29:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Depart generated by hbm2java
 */
public class Depart implements java.io.Serializable {

	private byte deptNo;
	private String dnombre;
	private String loc;
	private Set emples = new HashSet(0);

	public Depart() {
	}

	public Depart(byte deptNo) {
		this.deptNo = deptNo;
	}

	public Depart(byte deptNo, String dnombre, String loc, Set emples) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
		this.emples = emples;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public Set getEmples() {
		return this.emples;
	}

	public void setEmples(Set emples) {
		this.emples = emples;
	}

}
